services:
  - type: web
    name: vehicle-maintenance-scheduler
    env: node
    rootDir: vehicle_maintenance_scheduler
    buildCommand: cd ../logging_middleware && npm install axios dotenv && cd ../vehicle_maintenance_scheduler && npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: API_BASE_URL
        value: http://20.207.122.201/evaluation-service
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false

  - type: web
    name: notification-app-backend
    env: node
    rootDir: notification_app_be
    buildCommand: cd ../logging_middleware && npm install axios dotenv && cd ../notification_app_be && npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: API_BASE_URL
        value: http://20.207.122.201/evaluation-service
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
